### ISSUE TITLE
play_with_dlatent.py StopIteration

### ISSUE THREAD

**Issue by nuckykk** [a312863063/seeprettyface-face_editor#10]
大神 求帮助

Traceback (most recent call last):
  File "play_with_dlatent.py", line 87, in <module>
    main()
  File "play_with_dlatent.py", line 44, in main
    generator = Generator(Gs_network, batch_size=1, randomize_noise=False)
  File "E:\stylegan2\stylegan2_application\humanfacegenerators\util\generator_model.py", line 52, in __init__
    self.dlatent_variable = next(v for v in tf.global_variables() if 'learnable_dlatents' in v.name)
StopIteration

**Comment by wgh1989** [comment]
@nuckykk 请问你解决了吗？我也遇到这个问题
