### ISSUE TITLE
play_with_dlatent.py AssertionError

### ISSUE THREAD

**Issue by dnc-anwang** [a312863063/seeprettyface-face_editor#14]
Traceback (most recent call last):
  File "play_with_dlatent.py", line 87, in <module>
    main()
  File "play_with_dlatent.py", line 43, in main
    generator_network, discriminator_network, Gs_network = pickle.load(f)
  File "D:\MyProjects\ai\seeprettyface-face_editor\dnnlib\tflib\network.py", line 279, in __setstate__
    assert state["version"] in [2, 3]
AssertionError

what's happening ?

**Comment by dnc-anwang** [comment]
I noticed stylegan2,  the code is :

assert state["version"] in [2, 3, 4] 

so it passed, then I encountered another question, cann't find dnnlib.tflib.ops,   so I copied some files from stylegan2.

such as: ops the whole directory,  and custom_ops.py.  

so it works, however, pictures generated by play_with_dlatent have no expect changes compared to the original one. 

why ?

**Comment by molo32** [comment]
I have the same problem assert state ["version"] in [2, 3] , did you solve it?

**Comment by zhang123-sys** [comment]
```bash
python play_with_dlatent.py
```
报错
`AttributeError: module 'tensorflow' has no attribute 'Dimension'`
tensorflow用什么版本？我的tensorflow和Keras均为2.10.0
